// Shared department list — used by the GR drafting form
// (DraftInputCard.jsx) and the admin officer form (Admin.jsx) so both
// stay in sync with the same set of departments. `value` matches the
// exact strings backend/config.py's DEPARTMENT_CODES dict keys off of.
export const DEPARTMENTS = [
  { value: "Agriculture,_Dairy_Development,_Animal_Husbandry_and_Fisheries_Department", label: "Agriculture, Dairy Development, Animal Husbandry & Fisheries" },
  { value: "Co-operation,_Textiles_and_Marketing_Department", label: "Co-operation, Textiles & Marketing" },
  { value: "Environment_Department", label: "Environment Department" },
  { value: "Finance_Department", label: "Finance Department" },
  { value: "Food,_Civil_Supplies_and_Consumer_Protection_Department", label: "Food, Civil Supplies & Consumer Protection" },
  { value: "General_Administration_Department", label: "General Administration Department" },
  { value: "Higher_and_Technical_Education_Department", label: "Higher & Technical Education" },
  { value: "Home_Department", label: "Home Department" },
  { value: "Housing_Department", label: "Housing Department" },
  { value: "Industries,_Energy_and_Labour_Department", label: "Industries, Energy & Labour" },
  { value: "Information_Technology_Department", label: "Information Technology Department" },
  { value: "Law_and_Judiciary_Department", label: "Law & Judiciary Department" },
  { value: "Marathi_Language_Department", label: "Marathi Language Department" },
  { value: "Medical_Education_and_Drugs_Department", label: "Medical Education & Drugs" },
  { value: "Minorities_Development_Department", label: "Minorities Development Department" },
  { value: "Other_Backward_Bahujan_Welfare_Department", label: "Other Backward Bahujan Welfare" },
  { value: "Parliamentary_Affairs_Department", label: "Parliamentary Affairs Department" },
  { value: "Persons_with_Disabilities_Welfare_Department", label: "Persons with Disabilities Welfare" },
  { value: "Planning_Department", label: "Planning Department" },
  { value: "Public_Health_Department", label: "Public Health Department" },
  { value: "Public_Works_Department", label: "Public Works Department" },
  { value: "Revenue_and_Forest_Department", label: "Revenue & Forest Department" },
  { value: "Rural_Development_Department", label: "Rural Development Department" },
  { value: "Skill_Development_and_Entrepreneurship_Department", label: "Skill Development & Entrepreneurship" },
  { value: "School_Education_and_Sports_Department", label: "School Education & Sports" },
  { value: "Social_Justice_and_Special_Assistance_Department", label: "Social Justice & Special Assistance" },
  { value: "Soil_and_Water_Conservation_Department", label: "Soil & Water Conservation" },
  { value: "Tourism_and_Cultural_Affairs_Department", label: "Tourism & Cultural Affairs" },
  { value: "Tribal_Development_Department", label: "Tribal Development Department" },
  { value: "Urban_Development_Department", label: "Urban Development Department" },
  { value: "Water_Resources_Department", label: "Water Resources Department" },
  { value: "Water_Supply_and_Sanitation_Department", label: "Water Supply & Sanitation" },
  { value: "Women_and_Child_Development_Department", label: "Women & Child Development" },
];
