"""generated_drafts is_saved flag

Revision ID: 864b1d6c071a
Revises: ee03568d47ea
Create Date: 2026-08-01 19:38:29.811665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864b1d6c071a'
down_revision: Union[str, Sequence[str], None] = 'ee03568d47ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_drafts', sa.Column('is_saved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###

    # Backfill: every draft that existed before this migration was already
    # visible in History under the old (always-visible) behaviour — treat
    # it as saved. Only drafts created after this point should start
    # hidden pending an explicit save.
    op.execute("UPDATE generated_drafts SET is_saved = true")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_drafts', 'is_saved')
    # ### end Alembic commands ###
