"""upload source, gr number counters, must change password

Revision ID: ee03568d47ea
Revises: fb5cbbd2205e
Create Date: 2026-08-01 13:51:19.167235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee03568d47ea'
down_revision: Union[str, Sequence[str], None] = 'fb5cbbd2205e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


draft_source_enum = postgresql.ENUM('generated', 'uploaded', name='draft_source', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    draft_source_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gr_number_counters',
    sa.Column('dept_code', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_seq', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('dept_code', 'year')
    )
    op.add_column('generated_drafts', sa.Column('source', draft_source_enum, server_default='generated', nullable=False))
    op.add_column('generated_drafts', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.create_index('ix_generated_drafts_source', 'generated_drafts', ['source'], unique=False)
    op.add_column('officers', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officers', 'must_change_password')
    op.drop_index('ix_generated_drafts_source', table_name='generated_drafts')
    op.drop_column('generated_drafts', 'original_filename')
    op.drop_column('generated_drafts', 'source')
    op.drop_table('gr_number_counters')
    # ### end Alembic commands ###

    bind = op.get_bind()
    draft_source_enum.drop(bind, checkfirst=True)
