"""initial schema

Revision ID: fb5cbbd2205e
Revises: 
Create Date: 2026-07-30 12:21:44.882135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb5cbbd2205e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


officer_role_enum = postgresql.ENUM('officer', 'reviewer', 'admin', name='officer_role', create_type=False)
draft_language_enum = postgresql.ENUM('en', 'mr', name='draft_language', create_type=False)
draft_status_enum = postgresql.ENUM('draft', 'under_review', 'finalised', 'archived', name='draft_status', create_type=False)
conflict_severity_enum = postgresql.ENUM('low', 'medium', 'high', name='conflict_severity', create_type=False)
conflict_detected_by_enum = postgresql.ENUM('rule_engine', 'llm_verifier', name='conflict_detected_by', create_type=False)
reference_script_enum = postgresql.ENUM('latin', 'devanagari', name='reference_script', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # gen_random_uuid() (used as the default for every primary key below)
    # is provided by pgcrypto.
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')

    bind = op.get_bind()
    officer_role_enum.create(bind, checkfirst=True)
    draft_language_enum.create(bind, checkfirst=True)
    draft_status_enum.create(bind, checkfirst=True)
    conflict_severity_enum.create(bind, checkfirst=True)
    conflict_detected_by_enum.create(bind, checkfirst=True)
    reference_script_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officers',
    sa.Column('officer_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('login_id', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=160), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('role', postgresql.ENUM('officer', 'reviewer', 'admin', name='officer_role', create_type=False), server_default='officer', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('officer_id')
    )
    op.create_index(op.f('ix_officers_login_id'), 'officers', ['login_id'], unique=True)
    op.create_table('generated_drafts',
    sa.Column('generated_draft_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('language', postgresql.ENUM('en', 'mr', name='draft_language', create_type=False), nullable=False),
    sa.Column('drafted_by', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_plain', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=160), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('gr_number', sa.String(length=64), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'under_review', 'finalised', 'archived', name='draft_status', create_type=False), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('template_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drafted_by'], ['officers.officer_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('generated_draft_id')
    )
    op.create_index('ix_generated_drafts_content_plain_fts', 'generated_drafts', [sa.literal_column("to_tsvector('english', coalesce(content_plain, ''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_generated_drafts_department_created_at', 'generated_drafts', ['department', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_generated_drafts_drafted_by'), 'generated_drafts', ['drafted_by'], unique=False)
    op.create_index(op.f('ix_generated_drafts_gr_number'), 'generated_drafts', ['gr_number'], unique=False)
    op.create_index('ix_generated_drafts_status', 'generated_drafts', ['status'], unique=False)
    op.create_table('draft_conflicts',
    sa.Column('conflict_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('generated_draft_id', sa.UUID(), nullable=False),
    sa.Column('source_of_conflict', sa.String(length=200), nullable=False),
    sa.Column('conflicting_text', sa.Text(), nullable=False),
    sa.Column('draft_excerpt', sa.Text(), nullable=True),
    sa.Column('conflicting_gr_id', sa.String(length=64), nullable=True),
    sa.Column('severity', postgresql.ENUM('low', 'medium', 'high', name='conflict_severity', create_type=False), server_default='medium', nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('detected_by', postgresql.ENUM('rule_engine', 'llm_verifier', name='conflict_detected_by', create_type=False), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_draft_id'], ['generated_drafts.generated_draft_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    op.create_index(op.f('ix_draft_conflicts_conflicting_gr_id'), 'draft_conflicts', ['conflicting_gr_id'], unique=False)
    op.create_index(op.f('ix_draft_conflicts_generated_draft_id'), 'draft_conflicts', ['generated_draft_id'], unique=False)
    op.create_index('ix_draft_conflicts_severity_active', 'draft_conflicts', ['severity'], unique=False, postgresql_where=sa.text('is_dismissed = false'))
    op.create_table('draft_references',
    sa.Column('reference_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('generated_draft_id', sa.UUID(), nullable=False),
    sa.Column('reference_text', sa.Text(), nullable=False),
    sa.Column('extracted_gr_number', sa.String(length=64), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('script', postgresql.ENUM('latin', 'devanagari', name='reference_script', create_type=False), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_draft_id'], ['generated_drafts.generated_draft_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reference_id')
    )
    op.create_index(op.f('ix_draft_references_generated_draft_id'), 'draft_references', ['generated_draft_id'], unique=False)
    op.create_table('draft_versions',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('generated_draft_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('edited_by', sa.UUID(), nullable=False),
    sa.Column('change_note', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['officers.officer_id'], ),
    sa.ForeignKeyConstraint(['generated_draft_id'], ['generated_drafts.generated_draft_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('generated_draft_id', 'version_number', name='uq_draft_version_number')
    )
    op.create_index(op.f('ix_draft_versions_generated_draft_id'), 'draft_versions', ['generated_draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_versions_generated_draft_id'), table_name='draft_versions')
    op.drop_table('draft_versions')
    op.drop_index(op.f('ix_draft_references_generated_draft_id'), table_name='draft_references')
    op.drop_table('draft_references')
    op.drop_index('ix_draft_conflicts_severity_active', table_name='draft_conflicts', postgresql_where=sa.text('is_dismissed = false'))
    op.drop_index(op.f('ix_draft_conflicts_generated_draft_id'), table_name='draft_conflicts')
    op.drop_index(op.f('ix_draft_conflicts_conflicting_gr_id'), table_name='draft_conflicts')
    op.drop_table('draft_conflicts')
    op.drop_index('ix_generated_drafts_status', table_name='generated_drafts')
    op.drop_index(op.f('ix_generated_drafts_gr_number'), table_name='generated_drafts')
    op.drop_index(op.f('ix_generated_drafts_drafted_by'), table_name='generated_drafts')
    op.drop_index('ix_generated_drafts_department_created_at', table_name='generated_drafts')
    op.drop_index('ix_generated_drafts_content_plain_fts', table_name='generated_drafts', postgresql_using='gin')
    op.drop_table('generated_drafts')
    op.drop_index(op.f('ix_officers_login_id'), table_name='officers')
    op.drop_table('officers')
    # ### end Alembic commands ###

    bind = op.get_bind()
    reference_script_enum.drop(bind, checkfirst=True)
    conflict_detected_by_enum.drop(bind, checkfirst=True)
    conflict_severity_enum.drop(bind, checkfirst=True)
    draft_status_enum.drop(bind, checkfirst=True)
    draft_language_enum.drop(bind, checkfirst=True)
    officer_role_enum.drop(bind, checkfirst=True)

    # Deliberately NOT dropping the pgcrypto extension: other
    # databases/schemas on the same Postgres instance may depend on it,
    # and CREATE EXTENSION IF NOT EXISTS in upgrade() is idempotent
    # regardless.
