import React, { createContext, useState, useContext, useEffect, useRef } from 'react';
import { useIsPresent } from 'framer-motion';

const translations = {
  en: {
    // Navbar
    nav_home: "Home",
    nav_draft: "Draft GR",
    nav_upload_gr: "Upload GR",
    nav_chat: "NIRN.Ai Chat",
    nav_conflicts: "Conflict Detection",
    nav_search: "Search",
    nav_analyze: "Analyze",
    nav_copilot: "NIRN.Ai Chat",
    nav_ai_copilot: "NIRN.Ai Chat →",
    nav_history: "History",
    nav_admin: "Admin",
    nav_login: "Officer Sign In",
    nav_logout: "Sign Out",

    // Login page
    login_heading: "Officer Sign In",
    login_tagline: "AI-assisted Government Resolution drafting & alignment",
    login_id_label: "Login ID",
    login_id_placeholder: "e.g. priya.sharma",
    login_password_label: "Password",
    login_show_password: "Show",
    login_hide_password: "Hide",
    login_submit: "Sign In",
    login_submitting: "Signing in…",
    login_error_generic: "Invalid login ID or password.",
    login_provisioned_note: "Accounts are provisioned by your department administrator.",
    login_returnto_note: "Sign in to continue.",

    // First-login password change
    change_password_heading: "Set a New Password",
    change_password_sub: "This is your first sign-in. Choose a new password before continuing.",
    change_password_current: "Current Password",
    change_password_new: "New Password",
    change_password_confirm: "Confirm New Password",
    change_password_submit: "Set Password & Continue",
    change_password_submitting: "Setting password…",
    change_password_mismatch: "The new passwords do not match.",
    change_password_too_short: "Password must be at least 10 characters.",
    change_password_success: "Password updated. Redirecting…",

    // Admin page
    admin_eyebrow: "Administration",
    admin_title: "Officer & Draft Administration",
    admin_tab_officers: "Officers",
    admin_tab_drafts: "All Drafts",
    admin_search_placeholder: "Search by name or login ID…",
    admin_filter_role: "Role",
    admin_filter_status: "Status",
    admin_filter_all: "All",
    admin_add_officer: "Add Officer",
    admin_col_name: "Name",
    admin_col_login_id: "Login ID",
    admin_col_department: "Department",
    admin_col_designation: "Designation",
    admin_col_role: "Role",
    admin_col_status: "Status",
    admin_col_last_login: "Last Login",
    admin_col_actions: "Actions",
    admin_status_active: "Active",
    admin_status_inactive: "Inactive",
    admin_action_edit: "Edit",
    admin_action_view_history: "View History",
    admin_action_deactivate: "Deactivate",
    admin_action_activate: "Activate",
    admin_action_reset_password: "Reset Password",
    admin_action_delete: "Delete",
    admin_never_logged_in: "Never",
    admin_modal_add_title: "Add Officer",
    admin_modal_edit_title: "Edit Officer",
    admin_field_name: "Full Name",
    admin_field_login_id: "Login ID",
    admin_field_department: "Department",
    admin_field_designation: "Designation",
    admin_field_role: "Role",
    admin_field_password: "Initial Password",
    admin_generate_password: "Generate strong password",
    admin_password_shown_once: "This password will not be shown again. Copy it now.",
    admin_copy: "Copy",
    admin_copied: "Copied",
    admin_save: "Save",
    admin_cancel: "Cancel",
    admin_confirm_delete_title: "Delete Officer",
    admin_confirm_delete_body: "This permanently deletes the officer account and cannot be undone.",
    admin_confirm_deactivate_title: "Deactivate Officer",
    admin_confirm_deactivate_body: "The officer will no longer be able to sign in. You can reactivate them later.",
    admin_confirm_reset_title: "Reset Password",
    admin_confirm_reset_body: "This immediately invalidates the officer's current password.",
    admin_has_drafts_warning: "This officer has {count} draft(s) and cannot be deleted. Deactivate instead.",
    admin_summary_total_drafts: "Total Drafts",
    admin_summary_unresolved: "Unresolved Conflicts",
    admin_summary_active_officers: "Active Officers",
    admin_summary_recent: "Drafts (Last 7 Days)",
    admin_filter_officer: "Officer",
    admin_no_officers: "No officers match your filters.",
    admin_no_drafts: "No drafts match your filters.",

    // History page
    history_eyebrow: "Draft History",
    history_title: "History",
    history_admin_viewing_banner: "Viewing draft history for {name}",
    history_admin_back_to_admin: "← Back to Admin",
    history_search_placeholder: "Search title or content…",
    history_filter_department: "Department",
    history_filter_status: "Status",
    history_col_gr_number: "GR Number",
    history_col_title: "Title",
    history_col_department: "Department",
    history_col_language: "Language",
    history_col_status: "Status",
    history_col_conflicts: "Conflicts",
    history_col_created: "Created",
    history_col_actions: "Actions",
    history_action_open: "Open",
    history_action_pdf: "PDF",
    history_action_docx: "DOCX",
    history_action_archive: "Archive",
    history_confirm_archive: "Archive this draft? It will be hidden from active views but not deleted.",
    history_empty_title: "No drafts yet",
    history_empty_desc: "Drafts you generate will appear here.",
    history_show_dismissed: "Show dismissed",
    history_no_conflicts: "No conflicts detected for this draft.",
    history_justification: "Justification:",
    history_dismissed_label: "Dismissed",
    history_dismiss_action: "Dismiss",
    history_dismiss_prompt: "Reason for dismissing this conflict (optional):",
    history_conflict_link_with_clauses: "{draftClause} of this draft ↔ {sourceClause} of GR {gr}",
    history_conflict_link_no_clauses: "This draft ↔ GR {gr}",
    history_conflicting_text: "Conflicting text (existing GR)",
    history_draft_excerpt: "This draft's text",
    status_draft: "Draft",
    status_under_review: "Under Review",
    status_finalised: "Finalised",
    status_archived: "Archived",
    severity_low: "Low",
    severity_medium: "Medium",
    severity_high: "High",

    // Export / save
    export_download_pdf: "Download PDF",
    export_download_docx: "Download DOCX",
    export_exporting: "Exporting…",
    export_error: "Export failed. Please try again.",
    save_unsaved_indicator: "Unsaved changes",
    save_saved_at: "Saved",
    save_unsaved_warning: "You have unsaved changes. Are you sure you want to leave?",

    // Upload GR
    upload_eyebrow: "POLICY ALIGNMENT & CONFLICT DETECTION",
    upload_title: "Upload GR",
    upload_sub: "Upload a GR document (.pdf, .docx, .txt) or paste resolution text to detect policy conflicts, cross-departmental clashes, and rule violations across 98,950+ Maharashtra GRs.",
    upload_dropzone_title: "Drag & drop your GR document here",
    upload_dropzone_sub: "Supports PDF (.pdf), Word (.docx), and Plain Text (.txt) up to 20 MB",
    upload_browse_btn: "Browse Files",
    upload_metadata_title: "Uploaded Document Metadata",
    upload_file_name: "File Name",
    upload_file_type: "Format",
    upload_file_pages: "Pages",
    upload_file_words: "Words",
    upload_file_chars: "Characters",
    upload_paste_label: "Or Paste GR Text Directly",
    upload_dept_label: "Issuing Department",
    upload_lang_label: "Language",
    upload_title_label: "Resolution Title / Subject",
    upload_text_label: "Extracted / Edit Resolution Text",
    upload_btn_analyze: "Analyze Policy Conflicts →",
    upload_btn_analyzing: "Analyzing Policy Conflicts...",
    upload_progress_uploading: "Uploading file...",
    upload_progress_extracting: "Extracting readable text...",
    upload_progress_preparing: "Preparing document clauses...",
    upload_progress_analyzing: "Running policy conflict analysis across 98,950+ GRs...",
    upload_clear_btn: "Clear & Start Over",
    upload_pdf_label: "Upload GR PDF",
    upload_pdf_uploading: "Extracting text...",
    upload_pdf_scanned_warning: "This PDF appears to be a scanned document — please paste the text manually. Image/scanned PDF support is not yet available.",
    upload_unsaved_warning: "You have unanalyzed or modified text. Are you sure you want to leave?",


    // Home
    home_headline: "Draft, Analyze, and Search",
    home_subheadline: "Intelligent drafting assistance, automatic conflict detection, and semantic search for Maharashtra Government Resolutions.",
    home_search_placeholder: "Search Maharashtra GRs (e.g., procurement rules, educational grants...)",
    home_gr_number_placeholder: "Enter exact GR ID (e.g., 202402281146457522)",
    home_gr_number_not_found: "GR not found in corpus. Please check the ID.",
    home_gr_number_searching: "Locating GR...",
    home_gr_number_result_title: "GR Found",
    home_try_search: "Try searching:",
    home_try_label: "Try asking:",
    home_title_1: "NIRN.Ai for ",
    home_title_2: "for Governance",
    home_title_line1: "NIRN.Ai for",
    home_title_line2: "GOVERNANCE",
    home_gr_lookup_label: "Look up by GR ID",
    home_gr_lookup_tooltip: "Enter a GR ID to look up a specific resolution directly.",
    home_stat_num: "98,950+",
    home_stat_label: "Government Resolutions",
    home_stat_sub: "Across departments. At your fingertips.",
    feat_search_title: "Semantic Search",
    feat_search_desc: "Understand natural language and find relevant GRs instantly.",
    feat_search_label: "Search now",
    feat_upload_title: "Upload & Analyze",
    feat_upload_desc: "Submit a draft GR and get AI-powered alignment checks instantly.",
    feat_upload_label: "Upload GR",
    feat_conflict_title: "Conflict Detection",
    feat_conflict_desc: "Flag clashes with existing resolutions across departments.",
    feat_conflict_label: "Explore",
    feat_template_title: "Template Checks",
    feat_template_desc: "Enforce the Manual of Office Procedure rule by rule.",
    feat_template_label: "View checks",
    home_sug_1: "GR about work from home policy",
    home_sug_2: "Leave rules for government employees",
    home_sug_3: "Latest circulars on procurement",

    // Search
    search_eyebrow: "Semantic Search",
    search_title: "Search the Corpus",
    search_sub: "Search past Government Resolutions by meaning, not keywords — a query about “late admission” finds “delayed enrolment procedure”.",
    search_placeholder: "e.g. lateral entry intake in technical institutions",
    search_searching: "Searching the corpus…",
    search_empty: "Results appear here. Try one of the suggestions on the home page.",
    search_result: "result",
    search_results: "results",
    search_view_source: "View source →",

    // Analyze
    analyze_eyebrow: "Upload & Analyze",
    analyze_title: "Draft Analysis",
    analyze_sub: "Paste a draft Government Resolution. NIRN.Ai checks it against the Manual of Office Procedure, resolves every citation, and flags conflicts with existing GRs across departments.",
    analyze_draft_title: "Draft GR",
    analyze_load_sample: "Load sample",
    analyze_label_title: "Title",
    analyze_label_dept: "Department",
    analyze_label_lang: "Language",
    analyze_label_body: "Draft text",
    analyze_btn: "Analyze draft →",
    analyze_empty: "The analysis report appears here. Load the sample draft to see it in action.",
    analyze_running: "Analyzing GR for conflicts...",
    analyze_status_clean: "Clean — ready to issue",
    analyze_status_review: "Needs review",
    analyze_status_blocked: "Blocked — resolve issues before issuing",
    analyze_card_template: "Template issues",
    analyze_card_ref: "References found",
    analyze_card_unresolved: "Unresolved refs",
    analyze_card_conflict: "Conflicts",
    analyze_sec_template: "Template compliance",
    analyze_sec_template_empty: "All Manual of Office Procedure rules passed.",
    analyze_sec_ref: "References",
    analyze_sec_ref_empty: "No GR citations found in the draft.",
    analyze_sec_conflict: "Cross-departmental conflicts",
    analyze_sec_conflict_empty: "No conflicts detected with existing GRs.",
    analyze_sec_terms: "Bilingual terminology",
    analyze_sec_terms_empty: "No terminology mappings produced.",
    analyze_fix: "Fix:",

    // Copilot
    copilot_chat_placeholder: "Ask anything about Government Resolutions...",
    copilot_clear_chat: "Clear chat",
    copilot_brief_title: "Your Brief",
    copilot_describe_label: "Describe the GR you need",
    copilot_describe_placeholder: "Describe the Government Resolution you would like to draft...",
    copilot_try_label: "Try:",
    copilot_generate_btn: "Generate GR →",
    copilot_start_over: "Start over",
    copilot_empty_title: "Your generated GR will appear here.",
    copilot_empty_desc: "Fill in the brief and click Generate.",
    copilot_loading_desc1: "Drafting your Government Resolution…",
    copilot_loading_desc2: "Referencing similar GRs from the corpus.",
    copilot_download: "Download .txt",
    copilot_download_pdf: "Download .pdf",
    copilot_dept: "Department:",
    copilot_out_lang_en: "Output Language: English",
    copilot_out_lang_mr: "Output Language: Marathi",
    copilot_analyze_draft: "Analyze this draft →",

    // Draft page
    draft_eyebrow: "AI drafting",
    draft_title: "Draft GR",
    draft_sub: "Your intelligent assistant for drafting, querying, and auditing Government Resolutions of Maharashtra.",
    draft_brief_title: "Draft Brief & Parameters",
    draft_brief_desc: "Describe the Government Resolution you need. NIRN.Ai will handle alignment, templates, and conflict checks.",
    draft_clear_fields: "Clear Fields",
    draft_clear_confirm: "Clear all fields? This cannot be undone.",
    draft_describe_label: "Describe the Resolution Brief",
    draft_describe_placeholder: "e.g. Issue a Government Resolution regarding financial assistance of ₹25,000 for university research labs...",
    draft_try_examples: "Try Example Briefs:",
    draft_issuing_dept: "Issuing Department",
    draft_select_dept: "Select a Department",
    draft_output_lang: "Output Language",
    draft_lang_english: "English",
    draft_lang_marathi: "मराठी (Marathi)",
    draft_generate_btn: "Generate Draft GR →",
    draft_generating: "Generating GR & Running Analysis...",
    draft_stage_brief: "Brief",
    draft_stage_generate: "Generate Draft",
    draft_stage_template: "Template Validation",
    draft_stage_conflict: "Conflict Detection",
    draft_stage_reference: "Reference Tracking",
    draft_stage_ready: "Ready for Review",
    draft_tab_mop: "MOP Rules",
    draft_tab_conflicts: "Policy Conflicts",
    draft_tab_references: "References",
    draft_tab_terminology: "Terminology",
    draft_tab_suggestions: "Suggestions",
    draft_pending: "Pending Draft",
    draft_viewer_empty_title: "Your generated Government Resolution will appear here.",
    draft_viewer_empty_desc: "Fill in the brief description on the left and click Generate Draft GR to begin the AI-assisted drafting workflow.",
    draft_viewer_loading_title: "Drafting Government Resolution...",
    draft_viewer_loading_desc: "Synthesizing retrieved GR templates, enforcing legal formatting, and performing conflict verification.",
    draft_official: "OFFICIAL DRAFT",
    draft_copy: "Copy",
    draft_copied: "Copied",
    draft_download_pdf: "PDF Print",
    draft_loading_taking_longer: "Taking longer than expected, please wait...",
    draft_loading_generating: "Generating Government Resolution...",
    draft_loading_retrieving: "Retrieving relevant GRs, enforcing template, and verifying conflicts",
    draft_download_conflict_report: "Download Conflict Report",
    draft_download_full_conflict_report: "Download Full Conflict Report PDF",
    draft_generating_pdf: "Generating PDF...",
    draft_resolve_all_conflicts: "Resolve All Conflicts",
    draft_resolving_conflicts: "Resolving",
    draft_all_conflicts_resolved: "All Conflicts Resolved",
    draft_resolved_badge: "Resolved",
    draft_resolved_conflict_with: "Resolved conflict with",
    draft_updated_clause_text: "Updated Clause Text:",
    draft_original_clause_text: "Original:",
    draft_resolve_one: "Resolve",
    draft_still_conflicting: "Still conflicting — needs manual review",
    draft_resolve_error: "Resolution attempt failed — needs manual review",

    // Chat page
    chat_eyebrow: "Ask anything",
    chat_title: "NIRN.Ai Chat",
    chat_sub: "Your intelligent assistant for querying and understanding Government Resolutions of Maharashtra.",
    chat_empty_title: "NIRN.Ai Copilot",
    chat_empty_sub: "Ask any question about Maharashtra Government Resolutions. I ground every answer in the actual GR corpus.",
    chat_starter_1: "What is the policy on lateral entry in technical colleges?",
    chat_starter_2: "Summarise the rules for government employee leave.",
    chat_starter_3: "Which department handles scholarship grievances?",
    chat_sources_used: "Sources used:",

    // Floating chat widget
    chat_widget_tooltip: "Ask NIRN.Ai",
    chat_widget_close: "Close chat",

    // Workflow stepper, mobile compact form
    draft_stage_compact_prefix: "Step",
    draft_stage_compact_of: "of",
  },
  mr: {
    // Navbar
    nav_home: "मुख्य पृष्ठ",
    nav_draft: "मसुदा तयार करा",
    nav_upload_gr: "जीआर अपलोड करा",
    nav_chat: "निर्णि.आय चॅट",
    nav_conflicts: "संघर्ष शोधन",
    nav_search: "शोध",
    nav_analyze: "विश्लेषण",
    nav_copilot: "निर्णि.आय चॅट",
    nav_ai_copilot: "निर्णि.आय चॅट →",
    nav_history: "इतिहास",
    nav_admin: "प्रशासन",
    nav_login: "अधिकारी लॉगिन",
    nav_logout: "साइन आउट",

    // Login page
    login_heading: "अधिकारी लॉगिन",
    login_tagline: "एआय-सहाय्यित शासन निर्णय मसुदा व सुसंगतता तपासणी",
    login_id_label: "लॉगिन आयडी",
    login_id_placeholder: "उदा. priya.sharma",
    login_password_label: "पासवर्ड",
    login_show_password: "दाखवा",
    login_hide_password: "लपवा",
    login_submit: "साइन इन करा",
    login_submitting: "साइन इन होत आहे…",
    login_error_generic: "अवैध लॉगिन आयडी किंवा पासवर्ड.",
    login_provisioned_note: "खाती तुमच्या विभाग प्रशासकाद्वारे तयार केली जातात.",
    login_returnto_note: "पुढे जाण्यासाठी साइन इन करा.",

    // First-login password change
    change_password_heading: "नवीन पासवर्ड सेट करा",
    change_password_sub: "हे तुमचे पहिले लॉगिन आहे. पुढे जाण्यापूर्वी नवीन पासवर्ड निवडा.",
    change_password_current: "सध्याचा पासवर्ड",
    change_password_new: "नवीन पासवर्ड",
    change_password_confirm: "नवीन पासवर्डची पुष्टी करा",
    change_password_submit: "पासवर्ड सेट करा आणि पुढे जा",
    change_password_submitting: "पासवर्ड सेट होत आहे…",
    change_password_mismatch: "नवीन पासवर्ड जुळत नाहीत.",
    change_password_too_short: "पासवर्ड किमान १० अक्षरांचा असावा.",
    change_password_success: "पासवर्ड अद्ययावत झाला. पुनर्निर्देशित करत आहे…",

    // Admin page
    admin_eyebrow: "प्रशासन",
    admin_title: "अधिकारी व मसुदा प्रशासन",
    admin_tab_officers: "अधिकारी",
    admin_tab_drafts: "सर्व मसुदे",
    admin_search_placeholder: "नाव किंवा लॉगिन आयडीने शोधा…",
    admin_filter_role: "भूमिका",
    admin_filter_status: "स्थिती",
    admin_filter_all: "सर्व",
    admin_add_officer: "अधिकारी जोडा",
    admin_col_name: "नाव",
    admin_col_login_id: "लॉगिन आयडी",
    admin_col_department: "विभाग",
    admin_col_designation: "पदनाम",
    admin_col_role: "भूमिका",
    admin_col_status: "स्थिती",
    admin_col_last_login: "शेवटचे लॉगिन",
    admin_col_actions: "क्रिया",
    admin_status_active: "सक्रिय",
    admin_status_inactive: "निष्क्रिय",
    admin_action_edit: "संपादित करा",
    admin_action_view_history: "इतिहास पहा",
    admin_action_deactivate: "निष्क्रिय करा",
    admin_action_activate: "सक्रिय करा",
    admin_action_reset_password: "पासवर्ड रीसेट करा",
    admin_action_delete: "हटवा",
    admin_never_logged_in: "कधीही नाही",
    admin_modal_add_title: "अधिकारी जोडा",
    admin_modal_edit_title: "अधिकारी संपादित करा",
    admin_field_name: "पूर्ण नाव",
    admin_field_login_id: "लॉगिन आयडी",
    admin_field_department: "विभाग",
    admin_field_designation: "पदनाम",
    admin_field_role: "भूमिका",
    admin_field_password: "प्रारंभिक पासवर्ड",
    admin_generate_password: "मजबूत पासवर्ड तयार करा",
    admin_password_shown_once: "हा पासवर्ड पुन्हा दाखवला जाणार नाही. आताच कॉपी करा.",
    admin_copy: "कॉपी करा",
    admin_copied: "कॉपी झाले",
    admin_save: "जतन करा",
    admin_cancel: "रद्द करा",
    admin_confirm_delete_title: "अधिकारी हटवा",
    admin_confirm_delete_body: "हे अधिकारी खाते कायमचे हटवते आणि पूर्ववत करता येणार नाही.",
    admin_confirm_deactivate_title: "अधिकारी निष्क्रिय करा",
    admin_confirm_deactivate_body: "अधिकारी यापुढे लॉगिन करू शकणार नाही. तुम्ही नंतर पुन्हा सक्रिय करू शकता.",
    admin_confirm_reset_title: "पासवर्ड रीसेट करा",
    admin_confirm_reset_body: "यामुळे अधिकाऱ्याचा सध्याचा पासवर्ड त्वरित अवैध होतो.",
    admin_has_drafts_warning: "या अधिकाऱ्याकडे {count} मसुदे आहेत आणि तो हटवता येणार नाही. त्याऐवजी निष्क्रिय करा.",
    admin_summary_total_drafts: "एकूण मसुदे",
    admin_summary_unresolved: "न सुटलेले संघर्ष",
    admin_summary_active_officers: "सक्रिय अधिकारी",
    admin_summary_recent: "मसुदे (मागील ७ दिवस)",
    admin_filter_officer: "अधिकारी",
    admin_no_officers: "तुमच्या फिल्टरशी जुळणारे कोणतेही अधिकारी नाहीत.",
    admin_no_drafts: "तुमच्या फिल्टरशी जुळणारे कोणतेही मसुदे नाहीत.",

    // History page
    history_eyebrow: "मसुदा इतिहास",
    history_title: "इतिहास",
    history_admin_viewing_banner: "{name} यांचा मसुदा इतिहास पाहत आहात",
    history_admin_back_to_admin: "← प्रशासनाकडे परत जा",
    history_search_placeholder: "शीर्षक किंवा मजकूर शोधा…",
    history_filter_department: "विभाग",
    history_filter_status: "स्थिती",
    history_col_gr_number: "शासन निर्णय क्रमांक",
    history_col_title: "शीर्षक",
    history_col_department: "विभाग",
    history_col_language: "भाषा",
    history_col_status: "स्थिती",
    history_col_conflicts: "संघर्ष",
    history_col_created: "तयार केले",
    history_col_actions: "क्रिया",
    history_action_open: "उघडा",
    history_action_pdf: "PDF",
    history_action_docx: "DOCX",
    history_action_archive: "संग्रहित करा",
    history_confirm_archive: "हा मसुदा संग्रहित करायचा? तो सक्रिय दृश्यांमधून लपवला जाईल पण हटवला जाणार नाही.",
    history_empty_title: "अद्याप कोणतेही मसुदे नाहीत",
    history_empty_desc: "तुम्ही तयार केलेले मसुदे येथे दिसतील.",
    history_show_dismissed: "नाकारलेले दाखवा",
    history_no_conflicts: "या मसुद्यासाठी कोणतेही संघर्ष आढळले नाहीत.",
    history_justification: "स्पष्टीकरण:",
    history_dismissed_label: "नाकारले",
    history_dismiss_action: "नाकारा",
    history_dismiss_prompt: "हा संघर्ष नाकारण्याचे कारण (ऐच्छिक):",
    history_conflict_link_with_clauses: "या मसुद्याचे {draftClause} ↔ शासन निर्णय {gr} चे {sourceClause}",
    history_conflict_link_no_clauses: "हा मसुदा ↔ शासन निर्णय {gr}",
    history_conflicting_text: "संघर्षकारी मजकूर (विद्यमान शासन निर्णय)",
    history_draft_excerpt: "या मसुद्यातील मजकूर",
    status_draft: "मसुदा",
    status_under_review: "पुनरावलोकनाधीन",
    status_finalised: "अंतिम",
    status_archived: "संग्रहित",
    severity_low: "कमी",
    severity_medium: "मध्यम",
    severity_high: "उच्च",

    // Export / save
    export_download_pdf: "PDF डाउनलोड करा",
    export_download_docx: "DOCX डाउनलोड करा",
    export_exporting: "निर्यात होत आहे…",
    export_error: "निर्यात अयशस्वी झाली. कृपया पुन्हा प्रयत्न करा.",
    save_unsaved_indicator: "जतन न केलेले बदल",
    save_saved_at: "जतन केले",
    save_unsaved_warning: "तुमच्याकडे जतन न केलेले बदल आहेत. तुम्हाला नक्की बाहेर पडायचे आहे का?",

    // Upload GR
    upload_eyebrow: "धोरण सुसंगतता आणि वाद शोध",
    upload_title: "शासन निर्णय (GR) अपलोड करा",
    upload_sub: "९८,९५०+ महाराष्ट्र शासन निर्णयांमध्ये धोरण विरोध आणि नियम उल्लंघनांचे विश्लेषण करण्यासाठी जीआर फाईल (.pdf, .docx, .txt) अपलोड करा किंवा मजकूर पेस्ट करा.",
    upload_dropzone_title: "तुमची जीआर फाईल येथे ड्रॉप करा",
    upload_dropzone_sub: "PDF (.pdf), Word (.docx), आणि Plain Text (.txt) फाईल्सना २० MB पर्यंत सपोर्ट आहे",
    upload_browse_btn: "फाईल निवडा",
    upload_metadata_title: "अपलोड केलेल्या दस्तऐवजाची माहिती",
    upload_file_name: "फाईलचे नाव",
    upload_file_type: "स्वरूप",
    upload_file_pages: "पृष्ठे",
    upload_file_words: "शब्द",
    upload_file_chars: "अक्षरे",
    upload_paste_label: "किंवा जीआर मजकूर थेट पेस्ट करा",
    upload_dept_label: "निर्गमित करणारा विभाग",
    upload_lang_label: "भाषा",
    upload_title_label: "शासन निर्णयाचे शीर्षक / विषय",
    upload_text_label: "प्राप्त / संपादित मजकूर",
    upload_btn_analyze: "धोरण विरोधांचे विश्लेषण करा →",
    upload_btn_analyzing: "विश्लेषण सुरू आहे...",
    upload_progress_uploading: "फाईल अपलोड होत आहे...",
    upload_progress_extracting: "मजकूर एक्सट्रॅक्ट होत आहे...",
    upload_progress_preparing: "दस्तऐवज तयार होत आहे...",
    upload_progress_analyzing: "९८,९५०+ जीआरमध्ये धोरण विरोधांची तपासणी होत आहे...",
    upload_clear_btn: "हटवा आणि पुन्हा सुरू करा",
    upload_pdf_label: "जीआर पीडीएफ अपलोड करा",
    upload_pdf_uploading: "मजकूर काढला जात आहे...",
    upload_pdf_scanned_warning: "ही पीडीएफ स्कॅन केलेली दिसते — कृपया मजकूर स्वहस्ते पेस्ट करा. स्कॅन केलेल्या पीडीएफसाठी अद्याप सुविधा उपलब्ध नाही.",
    upload_unsaved_warning: "तुमच्याकडे विश्लेषित न केलेला किंवा सुधारित मजकूर आहे. तुम्हाला नक्की बाहेर पडायचे आहे का?",


    // Home
    home_headline: "मसुदा तयार करा, विश्लेषण करा आणि शोधा",
    home_subheadline: "महाराष्ट्र शासन निर्णयांसाठी बुद्धिमान मसुदा सहाय्य, स्वयंचलित संघर्ष शोध आणि अर्थपूर्ण शोध.",
    home_search_placeholder: "महाराष्ट्र शासन निर्णय शोधा (उदा., खरेदी नियम, शैक्षणिक अनुदान...)",
    home_gr_number_placeholder: "अचूक शासन निर्णय क्रमांक प्रविष्ट करा (उदा., 202402281146457522)",
    home_gr_number_not_found: "संग्रहात शासन निर्णय आढळला नाही. कृपया आयडी तपासा.",
    home_gr_number_searching: "शासन निर्णय शोधत आहे...",
    home_gr_number_result_title: "शासन निर्णय सापडला",
    home_try_search: "शोधण्याचा प्रयत्न करा:",
    home_try_label: "विचारण्याचा प्रयत्न करा:",
    home_title_1: "सुशासनासाठी ",
    home_title_2: "सुशासनासाठी",
    home_title_line1: "NIRN.Ai —",
    home_title_line2: "सुशासनासाठी",
    home_gr_lookup_label: "शासन निर्णय क्रमांकाने शोधा",
    home_gr_lookup_tooltip: "विशिष्ट शासन निर्णय थेट शोधण्यासाठी त्याचा आयडी प्रविष्ट करा.",
    home_stat_num: "९८,९५०+",
    home_stat_label: "शासन निर्णय",
    home_stat_sub: "विविध विभागांचे. तुमच्या बोटांच्या टोकावर.",
    feat_search_title: "अर्थपूर्ण शोध",
    feat_search_desc: "नैसर्गिक भाषा समजून घ्या आणि संबंधित शासन निर्णय त्वरित शोधा.",
    feat_search_label: "आता शोधा",
    feat_upload_title: "अपलोड आणि विश्लेषण",
    feat_upload_desc: "मसुदा शासन निर्णय सबमिट करा आणि त्वरित तपासणी मिळवा.",
    feat_upload_label: "शासन निर्णय अपलोड करा",
    feat_conflict_title: "संघर्ष शोध",
    feat_conflict_desc: "विभागांमधील विद्यमान शासन निर्णयांसह संघर्ष ओळखा.",
    feat_conflict_label: "अन्वेषण करा",
    feat_template_title: "टेम्पलेट तपासणी",
    feat_template_desc: "कार्यालयीन कार्यपद्धतीच्या नियमांची अंमलबजावणी करा.",
    feat_template_label: "तपासणी पहा",
    home_sug_1: "घरातून काम करण्याच्या धोरणाबाबत शासन निर्णय",
    home_sug_2: "शासकीय कर्मचाऱ्यांसाठी रजेचे नियम",
    home_sug_3: "खरेदीबाबतची नवीनतम परिपत्रके",

    // Search
    search_eyebrow: "अर्थपूर्ण शोध",
    search_title: "संग्रह शोधा",
    search_sub: "मागील शासन निर्णय अर्थानुसार शोधा, केवळ कीवर्डने नाही — 'late admission' बद्दलचा प्रश्न 'delayed enrolment procedure' शोधेल.",
    search_placeholder: "उदा. तांत्रिक संस्थांमध्ये लॅटरल एंट्री प्रवेश",
    search_searching: "संग्रहात शोधत आहे…",
    search_empty: "निकाल येथे दिसतील. मुख्य पृष्ठावरील सूचनांपैकी एक वापरून पहा.",
    search_result: "निकाल",
    search_results: "निकाल",
    search_view_source: "स्रोत पहा →",

    // Analyze
    analyze_eyebrow: "अपलोड आणि विश्लेषण",
    analyze_title: "मसुदा विश्लेषण",
    analyze_sub: "मसुदा शासन निर्णय पेस्ट करा. NIRN.Ai कार्यालयीन कार्यपद्धती मॅन्युअलनुसार तपासते, संदर्भ सोडवते आणि संघर्ष ओळखते.",
    analyze_draft_title: "मसुदा शासन निर्णय",
    analyze_load_sample: "नमुना लोड करा",
    analyze_label_title: "शीर्षक",
    analyze_label_dept: "विभाग",
    analyze_label_lang: "भाषा",
    analyze_label_body: "मसुदा मजकूर",
    analyze_btn: "मसुद्याचे विश्लेषण करा →",
    analyze_empty: "विश्लेषण अहवाल येथे दिसेल. कृतीत पाहण्यासाठी नमुना मसुदा लोड करा.",
    analyze_running: "सर्व चार तपासण्या चालवत आहे…",
    analyze_status_clean: "स्वच्छ — जारी करण्यास तयार",
    analyze_status_review: "पुनरावलोकनाची आवश्यकता आहे",
    analyze_status_blocked: "अवरोधित — जारी करण्यापूर्वी समस्या सोडवा",
    analyze_card_template: "टेम्पलेट समस्या",
    analyze_card_ref: "संदर्भ सापडले",
    analyze_card_unresolved: "न सुटलेले संदर्भ",
    analyze_card_conflict: "संघर्ष",
    analyze_sec_template: "टेम्पलेट अनुपालन",
    analyze_sec_template_empty: "सर्व कार्यालयीन कार्यपद्धती मॅन्युअल नियम उत्तीर्ण झाले.",
    analyze_sec_ref: "संदर्भ",
    analyze_sec_ref_empty: "मसुद्यात कोणतेही शासन निर्णय संदर्भ आढळले नाहीत.",
    analyze_sec_conflict: "विभागांमधील संघर्ष",
    analyze_sec_conflict_empty: "विद्यमान शासन निर्णयांसह कोणताही संघर्ष आढळला नाही.",
    analyze_sec_terms: "द्विभाषिक पारिभाषिक शब्दावली",
    analyze_sec_terms_empty: "कोणतेही पारिभाषिक मॅपिंग तयार केले नाही.",
    analyze_fix: "दुरुस्त करा:",

    // Copilot
    copilot_chat_placeholder: "शासन निर्णयांबद्दल काहीही विचारा...",
    copilot_clear_chat: "चॅट साफ करा",
    copilot_brief_title: "तुमचा मसुदा",
    copilot_describe_label: "तुमचा शासन निर्णय थोडक्यात मांडा",
    copilot_describe_placeholder: "तयार करावयाच्या शासन निर्णयाचे संक्षिप्त वर्णन येथे लिहा...",
    copilot_try_label: "प्रयत्न करा:",
    copilot_generate_btn: "शासन निर्णय तयार करा →",
    copilot_start_over: "पुन्हा सुरू करा",
    copilot_empty_title: "तुमचा शासन निर्णय येथे दिसेल.",
    copilot_empty_desc: "संक्षिप्त वर्णन भरा आणि जनरेट वर क्लिक करा.",
    copilot_loading_desc1: "तुमचा शासन निर्णय तयार करत आहे…",
    copilot_loading_desc2: "संग्रहातील समान शासन निर्णयांचा संदर्भ घेत आहे.",
    copilot_download: "डाउनलोड करा (.txt)",
    copilot_download_pdf: "डाउनलोड करा (.pdf)",
    copilot_dept: "विभाग:",
    copilot_out_lang_en: "आउटपुट भाषा: इंग्रजी",
    copilot_out_lang_mr: "आउटपुट भाषा: मराठी",
    copilot_analyze_draft: "या मसुद्याचे विश्लेषण करा →",

    // Draft page
    draft_eyebrow: "एआय मसुदा",
    draft_title: "शासन निर्णयाचा मसुदा तयार करा",
    draft_sub: "महाराष्ट्राच्या शासन निर्णयांचा मसुदा तयार करणे, चौकशी करणे आणि तपासणीसाठी तुमचा बुद्धिमान सहाय्यक.",
    draft_brief_title: "मसुदा संक्षिप्त माहिती व घटक",
    draft_brief_desc: "तुम्हाला आवश्यक असलेल्या शासन निर्णयाचे वर्णन करा. NIRN.Ai अनुरूपता, टेम्पलेट व संघर्ष तपासणी हाताळेल.",
    draft_clear_fields: "फील्ड साफ करा",
    draft_clear_confirm: "सर्व फील्ड साफ करायची आहेत का? ही क्रिया पूर्ववत करता येणार नाही.",
    draft_describe_label: "मसुद्याचे संक्षिप्त वर्णन लिहा",
    draft_describe_placeholder: "उदा. विद्यापीठ संशोधन प्रयोगशाळांसाठी ₹२५,००० आर्थिक सहाय्याबाबत शासन निर्णय जारी करा...",
    draft_try_examples: "नमुना संक्षिप्त माहिती वापरून पहा:",
    draft_issuing_dept: "जारी करणारा विभाग",
    draft_select_dept: "विभाग निवडा",
    draft_output_lang: "आउटपुट भाषा",
    draft_lang_english: "इंग्रजी (English)",
    draft_lang_marathi: "मराठी",
    draft_generate_btn: "मसुदा तयार करा →",
    draft_generating: "शासन निर्णय तयार करत आहे व विश्लेषण चालवत आहे...",
    draft_stage_brief: "संक्षिप्त माहिती",
    draft_stage_generate: "मसुदा तयार करा",
    draft_stage_template: "टेम्पलेट पडताळणी",
    draft_stage_conflict: "संघर्ष शोध",
    draft_stage_reference: "संदर्भ मागोवा",
    draft_stage_ready: "पुनरावलोकनासाठी तयार",
    draft_tab_mop: "कार्यपद्धती नियम",
    draft_tab_conflicts: "धोरण संघर्ष",
    draft_tab_references: "संदर्भ",
    draft_tab_terminology: "पारिभाषिक शब्दावली",
    draft_tab_suggestions: "सूचना",
    draft_pending: "मसुदा प्रलंबित",
    draft_viewer_empty_title: "तुमचा तयार केलेला शासन निर्णय येथे दिसेल.",
    draft_viewer_empty_desc: "डावीकडे संक्षिप्त वर्णन भरा आणि एआय-सहाय्यित मसुदा प्रक्रिया सुरू करण्यासाठी 'मसुदा तयार करा' वर क्लिक करा.",
    draft_viewer_loading_title: "शासन निर्णय तयार करत आहे...",
    draft_viewer_loading_desc: "पुनर्प्राप्त शासन निर्णय टेम्पलेट्सचे संश्लेषण, कायदेशीर स्वरूपन आणि संघर्ष पडताळणी करत आहे.",
    draft_official: "अधिकृत मसुदा",
    draft_copy: "कॉपी करा",
    draft_copied: "कॉपी झाले",
    draft_download_pdf: "पीडीएफ प्रिंट",
    draft_loading_taking_longer: "अपेक्षेपेक्षा जास्त वेळ लागत आहे, कृपया प्रतीक्षा करा...",
    draft_loading_generating: "शासन निर्णय तयार करत आहे...",
    draft_loading_retrieving: "संबंधित शासन निर्णय शोधत आहे, टेम्पलेट लागू करत आहे, संघर्ष तपासत आहे",
    draft_download_conflict_report: "संघर्ष अहवाल डाउनलोड करा",
    draft_download_full_conflict_report: "संपूर्ण संघर्ष अहवाल PDF डाउनलोड करा",
    draft_generating_pdf: "पीडीएफ तयार करत आहे...",
    draft_resolve_all_conflicts: "सर्व संघर्ष निराकरण करा",
    draft_resolving_conflicts: "निराकरण करत आहे",
    draft_all_conflicts_resolved: "सर्व संघर्ष निराकरण झाले",
    draft_resolved_badge: "निराकरण झाले",
    draft_resolved_conflict_with: "यांच्याशी संघर्ष निराकरण झाला:",
    draft_updated_clause_text: "अद्ययावत मजकूर:",
    draft_original_clause_text: "मूळ मजकूर:",
    draft_resolve_one: "निराकरण करा",
    draft_still_conflicting: "अद्याप संघर्ष कायम — मॅन्युअल तपासणी आवश्यक",
    draft_resolve_error: "निराकरणाचा प्रयत्न अयशस्वी — मॅन्युअल तपासणी आवश्यक",

    // Chat page
    chat_eyebrow: "काहीही विचारा",
    chat_title: "निर्णि.आय चॅट",
    chat_sub: "महाराष्ट्राच्या शासन निर्णयांबद्दल चौकशी करण्यासाठी व समजून घेण्यासाठी तुमचा बुद्धिमान सहाय्यक.",
    chat_empty_title: "निर्णि.आय कोपायलट",
    chat_empty_sub: "महाराष्ट्र शासन निर्णयांबद्दल कोणताही प्रश्न विचारा. मी प्रत्येक उत्तर वास्तविक शासन निर्णय संग्रहावर आधारित देतो.",
    chat_starter_1: "तांत्रिक महाविद्यालयांमध्ये लॅटरल एंट्रीबाबत धोरण काय आहे?",
    chat_starter_2: "शासकीय कर्मचाऱ्यांच्या रजेच्या नियमांचा सारांश द्या.",
    chat_starter_3: "शिष्यवृत्ती तक्रारी कोणता विभाग हाताळतो?",
    chat_sources_used: "वापरलेले स्रोत:",

    // Floating chat widget
    chat_widget_tooltip: "NIRN.Ai ला विचारा",
    chat_widget_close: "चॅट बंद करा",

    // Workflow stepper, mobile compact form
    draft_stage_compact_prefix: "पायरी",
    draft_stage_compact_of: "पैकी",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [siteLanguage, setSiteLanguage] = useState(
    localStorage.getItem('siteLanguage') || 'en'
  );

  useEffect(() => {
    localStorage.setItem('siteLanguage', siteLanguage);
    document.documentElement.lang = siteLanguage;
  }, [siteLanguage]);

  const toggleLanguage = () => {
    setSiteLanguage(prev => prev === 'en' ? 'mr' : 'en');
  };

  const t = (key) => {
    return translations[siteLanguage][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ siteLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  let isPresent = true;
  try {
    isPresent = useIsPresent();
  } catch (e) {
    // ignore
  }

  const saved = useRef({
    siteLanguage: context.siteLanguage,
    t: context.t,
  });

  if (isPresent) {
    saved.current = {
      siteLanguage: context.siteLanguage,
      t: context.t,
    };
  }

  return {
    ...context,
    siteLanguage: saved.current.siteLanguage,
    t: saved.current.t,
  };
}
