/**
 * grFormat.js — Helper utility to convert raw text GR generated by AI into structured HTML
 * for Tiptap rich text editor while preserving official government document layout.
 */

export function convertGRToHTML(plainText, language = 'marathi') {
  if (!plainText || typeof plainText !== 'string') {
    return '<p></p>';
  }

  const trimmed = plainText.trim();
  // If already formatted HTML, return as-is
  if (trimmed.startsWith('<p') || trimmed.startsWith('<div') || trimmed.startsWith('<h') || trimmed.startsWith('<table')) {
    return plainText;
  }

  const lines = trimmed.split('\n');
  const htmlParts = [];
  let inHeaderSection = true;

  const knownHeadingsRegex = /^(वाचा:|प्रस्तावना:|शासन निर्णय:|शासन परिपत्रक:|शासन शुद्धिपत्रक:|प्रत,|संदर्भ:|टीप:|परिशिष्ट|READ:|PREAMBLE:|GOVERNMENT RESOLUTION:|ORDER:|COPY TO:|REFERENCE:|NOTE:)/i;
  const closingRegex = /(महाराष्ट्राचे राज्यपाल|Governor of Maharashtra|आदेशानुसार व नावाने|By order and in the name|आपला|आपली|Yours faithfully)/i;
  const clauseRegex = /^(\d+|[\u0966-\u096F]+|\([0-9\u0966-\u096F]+\))[.)\s]/;
  const headerKeywordsRegex = /(महाराष्ट्र शासन|Government of Maharashtra|मंत्रालय|Mantralaya|मुंबई|Mumbai|विभाग|Department|क्रमांक|No\.|दिनांक|Date)/i;

  let currentBodyBuffer = [];

  const flushBodyBuffer = () => {
    if (currentBodyBuffer.length > 0) {
      const mergedParagraph = currentBodyBuffer.join(' ').replace(/\s+/g, ' ').trim();
      if (mergedParagraph) {
        htmlParts.push(`<p style="text-align: justify; margin-bottom: 12px;">${escapeHtml(mergedParagraph)}</p>`);
      }
      currentBodyBuffer = [];
    }
  };

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = rawLine.trim();

    if (!line) {
      flushBodyBuffer();
      continue;
    }

    // Check if we hit the main body heading or first reading heading
    if (inHeaderSection && (knownHeadingsRegex.test(line) || line.includes('शासन निर्णय') || line.includes('GOVERNMENT RESOLUTION'))) {
      flushBodyBuffer();
      if (line.includes('शासन निर्णय') || line.includes('GOVERNMENT RESOLUTION')) {
        htmlParts.push(`<h2 style="text-align: center;"><strong><u>${escapeHtml(line)}</u></strong></h2>`);
        inHeaderSection = false;
        continue;
      }
      inHeaderSection = false;
    }

    // 1. Header Block Lines (Top portion of document)
    if (inHeaderSection && headerKeywordsRegex.test(line)) {
      flushBodyBuffer();
      htmlParts.push(`<p style="text-align: center;"><strong>${escapeHtml(line)}</strong></p>`);
      continue;
    }

    // 2. Section Headings (वाचा:, प्रस्तावना:, शासन निर्णय:, etc.)
    if (knownHeadingsRegex.test(line)) {
      flushBodyBuffer();
      htmlParts.push(`<p style="margin-top: 16px; margin-bottom: 8px;"><strong><u>${escapeHtml(line)}</u></strong></p>`);
      continue;
    }

    // 3. Closing / Signatory lines
    if (closingRegex.test(line) || (i > lines.length - 6 && (line.startsWith('(') || line.includes('सचिव') || line.includes('Secretary') || line.includes('कार्यासन') || line.includes('Officer')))) {
      flushBodyBuffer();
      htmlParts.push(`<p style="text-align: right; margin-top: 12px; margin-bottom: 4px;"><strong>${escapeHtml(line)}</strong></p>`);
      continue;
    }

    // 4. Numbered operative clauses (०१., ०२., 1., 2.)
    if (clauseRegex.test(line)) {
      flushBodyBuffer();
      const match = line.match(clauseRegex);
      const prefix = match ? match[0] : '';
      const rest = line.slice(prefix.length).trim();
      htmlParts.push(`<p style="text-align: justify; margin-bottom: 8px;"><strong>${escapeHtml(prefix)}</strong> ${escapeHtml(rest)}</p>`);
      continue;
    }

    // 5. Default body line — accumulate into current paragraph buffer
    currentBodyBuffer.push(line);
  }

  flushBodyBuffer();

  return htmlParts.join('');
}

function escapeHtml(text) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
